name: Test All Fields

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - run: pip install yfinance pandas
      
      - run: python scripts/test_yfinance_all_fields.py
      
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output/
