#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WordPress連携: 登録済み企業リスト取得スクリプト
Fetch registered companies from WordPress REST API

Purpose:
- WordPress REST APIから登録済み企業を取得
- 証券コード（Ticker）を抽出
- CSVファイルに保存してfetch_stock_history.pyで使用

Author: Auto-generated by Claude Code
Date: 2025-01-04
"""

import os
import sys
import csv
import requests
import time
from datetime import datetime

# ============================================
# 設定
# ============================================

# WordPress REST API設定
WORDPRESS_API_URL = "https://japanir.jp/wp-json/wp/v2/company"
REQUEST_TIMEOUT = 30  # タイムアウト（秒）
MAX_RETRIES = 3  # リトライ回数
MAX_PAGES = 50  # 最大取得ページ数（100社/ページ × 50 = 最大5000社）

# 出力ファイル
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "data", "wordpress_companies.csv")

# ============================================
# WordPress REST APIから企業リストを取得
# ============================================

def fetch_wordpress_companies():
    """
    WordPress REST APIから登録済み企業を取得

    Returns:
        list: 企業データのリスト [{code, name, ticker}, ...]
    """
    print("=" * 60)
    print("WordPress連携: 登録済み企業リスト取得")
    print("=" * 60)
    print(f"API URL: {WORDPRESS_API_URL}")
    print()

    all_companies = []
    page = 1
    per_page = 100  # 1ページあたりの取得数

    while page <= MAX_PAGES:
        print(f"📥 ページ {page}/{MAX_PAGES} を取得中...")

        params = {
            "per_page": per_page,
            "page": page,
            "_fields": "id,title,stock_code",  # 必要なフィールドのみ取得
            "status": "publish"  # 公開済みのみ
        }

        # リトライ処理
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = requests.get(
                    WORDPRESS_API_URL,
                    params=params,
                    timeout=REQUEST_TIMEOUT
                )

                if response.status_code == 200:
                    companies = response.json()

                    if not companies:
                        print(f"✅ 全ページ取得完了（ページ {page - 1} まで）")
                        return all_companies

                    # データを抽出
                    for company in companies:
                        try:
                            # stock_codeフィールドから証券コードを取得
                            code = company.get('stock_code', '')

                            # stock_codeが存在する場合のみ追加
                            if code:
                                # 数字4桁のみ許可
                                if isinstance(code, str) and code.isdigit() and len(code) == 4:
                                    all_companies.append({
                                        'code': code,
                                        'name': company.get('title', {}).get('rendered', ''),
                                        'ticker': f"{code}.T"  # yfinance形式に変換
                                    })
                                else:
                                    print(f"  ⚠️  無効な証券コード: {code} (ID: {company.get('id')})")
                        except Exception as e:
                            print(f"  ❌ データ解析エラー (ID: {company.get('id')}): {str(e)}")
                            continue

                    print(f"  ✅ {len(companies)}件取得（累計: {len(all_companies)}社）")
                    page += 1
                    time.sleep(0.5)  # レート制限対策
                    break

                elif response.status_code == 400:
                    # ページ範囲外（最終ページ到達）
                    print(f"✅ 全ページ取得完了（ページ {page - 1} まで）")
                    return all_companies

                else:
                    print(f"  ⚠️  HTTPエラー: {response.status_code}")
                    if attempt < MAX_RETRIES:
                        print(f"  🔄 リトライ {attempt}/{MAX_RETRIES}...")
                        time.sleep(2 ** attempt)  # 指数バックオフ
                    else:
                        print(f"  ❌ {MAX_RETRIES}回リトライ失敗")
                        return all_companies

            except requests.exceptions.Timeout:
                print(f"  ⏱️  タイムアウト")
                if attempt < MAX_RETRIES:
                    print(f"  🔄 リトライ {attempt}/{MAX_RETRIES}...")
                    time.sleep(2 ** attempt)
                else:
                    print(f"  ❌ {MAX_RETRIES}回リトライ失敗")
                    return all_companies

            except Exception as e:
                print(f"  ❌ リクエストエラー: {str(e)}")
                if attempt < MAX_RETRIES:
                    print(f"  🔄 リトライ {attempt}/{MAX_RETRIES}...")
                    time.sleep(2 ** attempt)
                else:
                    print(f"  ❌ {MAX_RETRIES}回リトライ失敗")
                    return all_companies

    # 最大ページ数に到達
    if page > MAX_PAGES:
        print()
        print(f"⚠️  最大ページ数 ({MAX_PAGES}ページ) に到達しました")
        print(f"📊 取得企業数: {len(all_companies)}社")

    return all_companies


def save_to_csv(companies):
    """
    企業リストをCSVファイルに保存

    Args:
        companies (list): 企業データのリスト

    Returns:
        bool: 保存成功時True
    """
    print()
    print("=" * 60)
    print("CSVファイル保存")
    print("=" * 60)

    if not companies:
        print("❌ 保存する企業データがありません")
        return False

    try:
        # dataディレクトリが存在しない場合は作成
        os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

        # CSVに保存
        with open(OUTPUT_FILE, 'w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['code', 'name', 'ticker'])
            writer.writeheader()
            writer.writerows(companies)

        print(f"✅ 保存完了: {OUTPUT_FILE}")
        print(f"📊 企業数: {len(companies)}社")

        # サンプル表示（最初の5社）
        print()
        print("📋 サンプル（最初の5社）:")
        for i, company in enumerate(companies[:5], 1):
            print(f"  {i}. {company['code']} - {company['name']} ({company['ticker']})")

        return True

    except Exception as e:
        print(f"❌ CSV保存エラー: {str(e)}")
        return False


# ============================================
# メイン処理
# ============================================

def main():
    """メイン処理"""
    start_time = time.time()

    try:
        # WordPress APIから企業リスト取得
        companies = fetch_wordpress_companies()

        if not companies:
            print()
            print("⚠️  取得した企業が0件です")
            print("原因:")
            print("  - WordPress APIが正しく設定されていない")
            print("  - 公開済み企業投稿が存在しない")
            print("  - stock_codeフィールドが設定されていない")
            sys.exit(1)

        # 重複チェック
        unique_codes = set()
        duplicates = []
        for company in companies:
            if company['code'] in unique_codes:
                duplicates.append(company['code'])
            unique_codes.add(company['code'])

        if duplicates:
            print()
            print(f"⚠️  重複する証券コード: {', '.join(duplicates)}")

        # CSVに保存
        if save_to_csv(companies):
            elapsed = time.time() - start_time
            print()
            print("=" * 60)
            print("✅ 処理完了")
            print("=" * 60)
            print(f"実行時間: {elapsed:.1f}秒")
            print(f"取得企業数: {len(companies)}社")
            print(f"出力ファイル: {OUTPUT_FILE}")
            print()
            print("次のステップ:")
            print("  1. fetch_stock_history.py を実行して株価履歴データを取得")
            print("  2. GitHub Actionsで自動更新を有効化")
            sys.exit(0)
        else:
            sys.exit(1)

    except KeyboardInterrupt:
        print()
        print("⚠️  ユーザーによる中断")
        sys.exit(1)
    except Exception as e:
        print()
        print(f"❌ 予期しないエラー: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
